### ISSUE TITLE
Any way to use username and password instead of token?

### ISSUE THREAD

**Issue by fluffyloopy** [denebu/discord-chat-exporter#1]

**Comment by denebu** [comment]
Hmm.. As far as I know, there is no way to get a *User-type* token using username and password via Discord *official* API, so the answer is, no.
If you want to use this tool, and you don't know how to get a Discord token, you may refer: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs

**Comment by denebu** [comment]
Closing due to low activity.
