### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by z0mbieslayer** [denebu/discord-chat-exporter#2]
So far, I love this tool. Very cool you were able to make something like this in python. I've already piped the output to a new json file each time with jq and I noticed that the newest messages are towards the top. Any way I can modify the code so that the newer messages stay to the bottom? I'm not very experienced with python, so this would further my understanding of how things like this work. Thanks in advance.

**Comment by z0mbieslayer** [comment]
Just found out I can sort them using jq, should've done more research.

**Comment by denebu** [comment]
Thank you for your compliment. Whenever you might think that you need some help, feel free to create new issues.
